### ISSUE TITLE
more user friendly

### ISSUE THREAD

**Issue by fancymax** [iammapping/alfred-uploader#1]
add something like this:

![2016112821722test.jpg](http://7xpbra.com1.z0.glb.clouddn.com/2016112821722test.jpg)

**Comment by iammapping** [comment]
Good suggestion. But alfred workflows did not like apps, the input is limited, it would be complex to add a more keyword like "uploadcheck". The check is not very necessary before upload. Using the wrong variables will automatically fail the upload, and the error message will output to clipboard. You can also toggle the alfred workflows debugging mode to watch the reason.
