### ISSUE TITLE
Is it possible to upload directly from clipboard?

### ISSUE THREAD

**Issue by tonyxu-io** [iammapping/alfred-uploader#2]

**Comment by iammapping** [comment]
Let me try.

**Comment by tonyxu-io** [comment]
I did some research and found out they are using pngpaste library on Mac.

**Comment by iammapping** [comment]
@tonyxu-io  Thanks, I'm trying to use apple script to convert image from clipboard to file, but it does't work right now 😅.

**Comment by tonyxu-io** [comment]
I tried using `pngpaste` library and it worked well. Here is my repo: https://github.com/tonyxu-io/Alfred-Workflow-Upload-S3

**Comment by iammapping** [comment]
@tonyxu-io Awesome. I have given up the AppleScript, it's terrible.

**Comment by tonyxu-io** [comment]
😀

**Comment by iammapping** [comment]
fc0a8873f0f75f250d9247e144c642d272e1fa1e
Supported. @tonyxu-io thanks.
